### ISSUE TITLE
Command 'Generate File Tree' resulted in an error: Cannot read properties of undefined (reading 'fsPath')

### ISSUE THREAD

**Issue by arnaudambro** [Marius4568/vscode-file-tree-generator#1]
Hello

I wanted to try out your extension but I got this error

![image](https://github.com/user-attachments/assets/ceaf36db-45c7-4483-b981-d44430a405c7)

Any idea ?

**Comment by Marius4568** [comment]
Hello Arnaud,

I apologize for the inconvenience.

It seems the error might be occurring because of how the command is being
invoked. The File Tree Generator is designed to work when you select a
specific folder. Here's the correct way to use it:

   1. In the VS Code Explorer (file tree on the left), locate the folder
   you want to generate a tree for.
   2. Right-click on the desired folder.
   3. In the context menu that appears, select "Generate file tree".

I added a quick video demonstrating the usage.

If you've been trying to use it from the Command Palette (Ctrl+Shift+P or
Cmd+Shift+P), that might explain the error you're seeing. The command needs
a selected folder context to work correctly.

If you're still encountering issues please let me know, and provide the
following information:

   - The exact steps you're taking to invoke the command
   - Your VS Code version
   - Any error other messages you see (preferably screenshots)

This will help me troubleshoot further if needed.

**Comment by arnaudambro** [comment]
alright thanks for the explanation !

**Comment by Marius4568** [comment]
No problem!
